=== joaquinpf/2dgames-2bsoft/trunk/Word Challenge/Resources/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT name (#PCDATA)>
<!ELEMENT starttime (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ELEMENT pointsNewLetters (#PCDATA)>
<!ELEMENT match EMPTY>
<!ATTLIST match
	amount CDATA #REQUIRED
	points CDATA #REQUIRED
	bonusTime CDATA #REQUIRED
>
<!ELEMENT language EMPTY>
<!ATTLIST language
	name CDATA #REQUIRED
	dictionary CDATA #REQUIRED
	flag CDATA #REQUIRED
	sprite CDATA #REQUIRED
	selsprite CDATA #REQUIRED
>
<!ELEMENT game ((name, config))>
<!ELEMENT config ((starttime, background, matches, languages))>
<!ELEMENT languages ((language+))>
<!ELEMENT matches ((match+))>

=== joaquinpf/2dgames-2bsoft/Word Challenge/resources/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE game SYSTEM "config.dtd">
<game>
	<name>Word Challenge</name>
	<config>
		<starttime>210</starttime>
		<background>../Word Challenge/resources/images/background.png</background>
		<pointsNewLetters>100</pointsNewLetters>
		<matches>
			<match amount="3" points="20" bonusTime="0"/>
			<match amount="4" points="25" bonusTime="4"/>
			<match amount="5" points="50" bonusTime="7"/>
			<match amount="6" points="100" bonusTime="10"/>
		</matches>
		<languages>
			<language name="spanish" dictionary="../Word Challenge/resources/dic/spanish-words.dic" flag="../Word Challenge/resources/images/spanish.png" 
			sprite="../Word Challenge/resources/images/spanishlangns.png" selsprite="../Word Challenge/resources/images/spanishlang.png"/>
			<language name="english" dictionary="../Word Challenge/resources/dic/english-words.dic" flag="../Word Challenge/resources/images/english.png" 
			sprite="../Word Challenge/resources/images/englishlangns.png" selsprite="../Word Challenge/resources/images/englishlang.png"/>
			<language name="italian" dictionary="../Word Challenge/resources/dic/italian-words.dic" flag="../Word Challenge/resources/images/italian.png" 
			sprite="../Word Challenge/resources/images/italianlangns.png" selsprite="../Word Challenge/resources/images/italianlang.png"/>
		</languages>
	</config>
</game>

=== joaquinpf/2dgames-2bsoft/trunk/Word Challenge/Resources/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE game SYSTEM "config.dtd">
<game>
	<name>Word Challenge</name>
	<config>
		<starttime>60</starttime>
		<background>Resources/images/background.png</background>
		<matches>
			<match amount="3" points="20" bonusTime="0"/>
			<match amount="4" points="40" bonusTime="4"/>
			<match amount="5" points="50" bonusTime="7"/>
			<match amount="6" points="70" bonusTime="10"/>
		</matches>
		<languages>
			<language name="spanish" dictionary="Resources/dic/spanish-words.dic" flag="Resources/images/spanish.png"/>
		</languages>
	</config>
</game>

=== joaquinpf/2dgames-2bsoft/trunk/Word Challenge/resources/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE game SYSTEM "config.dtd">
<game>
	<name>Word Challenge</name>
	<config>
		<starttime>210</starttime>
		<background>resources/images/background.png</background>
		<pointsNewLetters>100</pointsNewLetters>
		<matches>
			<match amount="3" points="20" bonusTime="0"/>
			<match amount="4" points="25" bonusTime="4"/>
			<match amount="5" points="50" bonusTime="7"/>
			<match amount="6" points="100" bonusTime="10"/>
		</matches>
		<languages>
			<language name="spanish" dictionary="resources/dic/spanish-words.dic" flag="resources/images/spanish.png" 
			sprite="resources/images/spanishlangns.png" selsprite="resources/images/spanishlang.png"/>
			<language name="english" dictionary="resources/dic/english-words.dic" flag="resources/images/english.png" 
			sprite="resources/images/englishlangns.png" selsprite="resources/images/englishlang.png"/>
			<language name="italian" dictionary="resources/dic/italian-words.dic" flag="resources/images/italian.png" 
			sprite="resources/images/italianlangns.png" selsprite="resources/images/italianlang.png"/>
		</languages>
	</config>
</game>

=== joaquinpf/2dgames-2bsoft/trunk/Word Challenge/resources/wordchallenge/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE game SYSTEM "config.dtd">
<game>
	<name>Word Challenge</name>
	<config>
		<starttime>210</starttime>
		<background>./resources/wordchallenge/images/background.png</background>
		<pointsNewLetters>100</pointsNewLetters>
		<matches>
			<match amount="3" points="20" bonusTime="0"/>
			<match amount="4" points="25" bonusTime="4"/>
			<match amount="5" points="50" bonusTime="7"/>
			<match amount="6" points="100" bonusTime="10"/>
		</matches>
		<languages>
			<language name="spanish" dictionary="./resources/wordchallenge/dic/spanish-words.dic" flag="./resources/wordchallenge/images/spanish.png" 
			sprite="./resources/wordchallenge/images/spanishlangns.png" selsprite="./resources/wordchallenge/images/spanishlang.png"/>
			<language name="english" dictionary="./resources/wordchallenge/dic/english-words.dic" flag="./resources/wordchallenge/images/english.png" 
			sprite="./resources/wordchallenge/images/englishlangns.png" selsprite="./resources/wordchallenge/images/englishlang.png"/>
			<language name="italian" dictionary="./resources/wordchallenge/dic/italian-words.dic" flag="./resources/wordchallenge/images/italian.png" 
			sprite="./resources/wordchallenge/images/italianlangns.png" selsprite="./resources/wordchallenge/images/italianlang.png"/>
		</languages>
	</config>
</game>
